-- Supabase Schema Generation Script (Version 3 - Synchronized with Real Schema)
-- Re-designed to match the exact schema from Supabase production

-- 1. product_descriptions
CREATE TABLE IF NOT EXISTS public.product_descriptions (
    product text PRIMARY KEY,
    "Description" text
);

-- 2. coloristas
CREATE TABLE IF NOT EXISTS public.coloristas (
    matricula text PRIMARY KEY,
    nome text,
    turno text
);

-- 3. paint_standards
CREATE TABLE IF NOT EXISTS public.paint_standards (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cad_code text UNIQUE,
    l numeric,
    a numeric,
    b numeric,
    created_at timestamp with time zone DEFAULT now()
);

-- 4. paint_inspections
CREATE TABLE IF NOT EXISTS public.paint_inspections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cad_code text,
    standard_l numeric,
    standard_a numeric,
    standard_b numeric,
    inspected_l numeric,
    inspected_a numeric,
    inspected_b numeric,
    delta_e numeric,
    status text,
    created_at timestamp with time zone DEFAULT now()
);

-- 5. pantone_standards
CREATE TABLE IF NOT EXISTS public.pantone_standards (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    "L" numeric,
    a numeric,
    b numeric
);

-- 6. products
CREATE TABLE IF NOT EXISTS public.products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    l numeric,
    a numeric,
    b numeric
);

-- 7. process_standards
CREATE TABLE IF NOT EXISTS public.process_standards (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code text,
    color_name text,
    dens_min numeric,
    dens_target numeric,
    dens_max numeric,
    tva_min numeric,
    tva_target numeric,
    tva_max numeric,
    anilox text,
    anilox_num text,
    dupla_face text,
    opac_min numeric,
    opac_target numeric,
    opac_max numeric,
    created_at timestamp with time zone DEFAULT now()
);

-- 8. color_inspections
CREATE TABLE IF NOT EXISTS public.color_inspections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula text,
    product text,
    original_l numeric,
    original_a numeric,
    original_b numeric,
    inspected_l numeric,
    inspected_a numeric,
    inspected_b numeric,
    deltae numeric,
    status text,
    bobina text,
    op integer,
    "timestamp" timestamp without time zone DEFAULT now(),
    colorista text,
    justification text
);

-- 9. inspecoes_processo
CREATE TABLE IF NOT EXISTS public.inspecoes_processo (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    perfil_densidade text,
    produto text,
    op_number text,
    bobina_filha_id text,
    status_geral text,
    densidade_c_medido numeric,
    densidade_m_medido numeric,
    densidade_y_medido numeric,
    densidade_k_medido numeric,
    tva_c_medido numeric,
    tva_m_medido numeric,
    tva_y_medido numeric,
    tva_k_medido numeric,
    opacidade_branco_medido numeric,
    medicoes_json jsonb,
    created_at timestamp with time zone DEFAULT now(),
    justification text,
    matricula text,
    colorista text
);

-- Security: Enable RLS and Create Public Access Policies
DO $$ 
DECLARE
    t text;
BEGIN
    FOR t IN SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' 
    LOOP
        -- Enable RLS
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t);
        
        -- Drop existing policy if any
        EXECUTE format('DROP POLICY IF EXISTS "Public Access" ON public.%I', t);
        
        -- Create permissive policy for ALL operations
        EXECUTE format('CREATE POLICY "Public Access" ON public.%I FOR ALL USING (true) WITH CHECK (true)', t);
    END LOOP;
END $$;
